### ISSUE TITLE
Does siri node works with iphone - ipad not jailbroken?

### ISSUE THREAD

**Issue by chesnel** [zhangyuanwei/node-siri#1]
I'm sorry I'm not very good in Chinese :) But is it possible to use siri node with an iphone - ipad not jailbroken? If so are you able to give me more explanation on how to operate? I use siriproxy Plamoni of the moment and am looking for a javascript equivalent with nodejs. Thank you in advance for your reply.

**Comment by yocontra** [comment]
Also curious about this and getting some basic english documentation - google for some reason refuses to translate this page :angry:

**Comment by zhangyuanwei** [comment]
Sorry,I will publish an english documentation as quickly as possible.

**Comment by chesnel** [comment]
don't be sorry :) I'm looking forward the documentation in English.

**Comment by jnovack** [comment]
@zhangyuanwei If you decide on a translation package ([dialect](https://github.com/masylum/dialect) might be easy), I can help translate.

**Comment by taitems** [comment]
I managed to translate the instructions and the answer looks similar to SiriProxy. No, you do not have to jailbreak your device. Instead you have to set up a VPN within your home network and route all traffic through that. Like SiriProxy, it appears it will fail once you leave your home network. 

This is all speculative and from translations. I'm yet to get it running myself, given the high barriers to entry (for a designer anyway).

**Comment by taitems** [comment]
Whoops, s/VPN/DNS

**For clarity, translated instructions:**

```
Think of ways to guzzoni.apple.com DNS resolves to run the 
agent machine (if you jailbreak, you can directly change the 
host. Did not escape, then, you can also set up a DNS proxy 
server and then modify the router's DNS server to achieve). 
Run sudo node install.js, Siri agent uses port 443, the detection 
interface uses port 80 (optional). By IOS device access 
http://guzzoni.apple.com, the system will automatically detect 
configuration.
```

**Comment by chesnel** [comment]
I'm trying to use with different address because the port 80 and 443 are already uses on my computer, and I have a error message for the DNS. Check entry for guzzoni.apple.com !
Any idea?

**Comment by JBX028** [comment]
Hi,

I would like to install this siri proxy on my Raspberry PI. Do i have to follow the same steps than for the real proxy running on top of ruby ? I can see a certificat as part of this repository but i am not sure to understand why. 

Who can quickly high level list the steps to install that proxy ?

Thanks in advance from a french fan

**Comment by jnovack** [comment]
@JBX028 
- Install NodeJS 0.10.7 (I am using this version, I know it works).
- Run `genca.sh`. Your **Common Name** MUST be `guzzoni.apple.com`
- Your iPad/iPhone needs to resolve `guzzoni.apple.com` to your Raspberry Pi, BUT your Raspberry Pi MUST resolve `guzzoni.apple.com` properly out to the Internet.  Your Raspberry Pi should have proper DNS servers.
- **OPTIONAL:** Edit `siri.js`, line 15.  `SIRI_DEBUG = true`.  This will help.
- **REQUIRED:** Edit `test/hello.js`, line 4.  Replace `/你好/` with `/Hello/` (or `/Bonjour/`).

**Comment by JBX028** [comment]
Hi,

This is exactly what i did and now i don't have any errors anymore but what i am saying is not catched. I've posted a reply to the other post.

Thanks a lot for the help you provided so far !!

**Comment by jnovack** [comment]
@chesnel Can you **Comment and Close** this ticket? I believe this is solved with the English documentation.
