### ISSUE TITLE
HTTPS-Service in fail with the new version

### ISSUE THREAD

**Issue by JBX028** [zhangyuanwei/node-siri#11]
Hi,

Under another directory, I have installed the new version of the proxy following the steps described in the README

When I run `node install.js`, Starting HTTPS-Service fails. When I run the same command from the previous directory where the old version of the proxy is running, everything is ok.

Not sure if it is important but i copied the previous certificats from the other directory.

Any ideas ?

**Comment by jnovack** [comment]
What is the output of `curl -i https://localhost:443`?

Also, did you run the commands and post a pastebin (or equivalent) of the results as described in the README?

**Comment by JBX028** [comment]
Finally it's (seems to be) probably a certificat issue...

``` bash
root@raspberrypi:/home/pi/Documents/node/siri2/node_modules/siri# curl -i https://localhost:443
curl: (60) SSL certificate problem: self signed certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by jnovack** [comment]
Nope, user error.  You already have something running on 443.  You can't have whatever you are running on 443 already AND `install.js` run on 443 at the same time.

**Comment by JBX028** [comment]
Strange. Nothing is shown on 443 via netstat and the same command works fine with the old version. Of course the old one is stopped when I run the most recent version. I'll kept the old one for the moment.

**Comment by jnovack** [comment]
Do not run the `install.js` before running the following commands:

```
curl -ik https://localhost:443
openssl s_client -connect localhost:443
```

IF you get:

```
$ curl -ik https://localhost:443
curl: (7) couldn't connect to host
$ openssl s_client -connect localhost:443
connect: Connection refused
connect:errno=61
```

Then there is no problem.

IF you get something else, then something else is running on 443.

**Comment by JBX028** [comment]
Hi,

I got the same result than you except that "errno" at the end, is not equal to 61 but to 111.

Thanks
