### ISSUE TITLE
启动HTTPS服务 失败

### ISSUE THREAD

**Issue by shuhongwu** [zhangyuanwei/node-siri#2]
你好，我在按照你的操作步骤来时，在把host文件里加上我的服务器地址后:
1,检测DNS解析 成功
2,启动HTTPS服务 失败

排查了很久，包含重启服务，重启手机，都不行~~~麻烦指点下啊~~~

**Comment by shuhongwu** [comment]
![IMG_0082](https://f.cloud.github.com/assets/674674/320191/76f8e382-9920-11e2-82e1-2df1fea78d23.PNG)

**Comment by zhangyuanwei** [comment]
服务器上nodejs的输出是什么？

**Comment by shuhongwu** [comment]
我把我的操作过程给你看下:
![1](https://f.cloud.github.com/assets/674674/326897/fdfcc33a-9b55-11e2-8bd4-8c31a65331ca.png)

**Comment by shuhongwu** [comment]
Open打开Safari浏览器:
![two](https://f.cloud.github.com/assets/674674/326898/71a0437a-9b56-11e2-8e4a-02dbad7aaabc.png)

之后服务器截图:
![Screen Shot 2013-04-02 at 1 26 38 PM](https://f.cloud.github.com/assets/674674/326906/90077d60-9b56-11e2-9afc-e39554625b5a.png)

一段时间后:启动HTTPS服务 [FAIL]

**Comment by zhangyuanwei** [comment]
找到问题了，是由于Nodejs不会自动断开已经链接的HTTP会话，已经通过destroy显式断开。应该解决了。

**Comment by shuhongwu** [comment]
我对Siri说“你好”后，Console里面的log信息为:
![Screen Shot 2013-04-05 at 2 03 11 PM](https://f.cloud.github.com/assets/674674/342612/993ebdbe-9db6-11e2-89d6-a676173ea1ea.png)

**Comment by shuhongwu** [comment]
证书都是安装好的
![IMG_0102](https://f.cloud.github.com/assets/674674/342615/fc1421cc-9db6-11e2-8070-0c9c3a12c0f9.PNG)
