### ISSUE TITLE
这个证书怎么生成呢？

### ISSUE THREAD

**Issue by shenshen** [zhangyuanwei/node-siri#3]
sudo node ./test/hello.js
不行啊~ wiki能具体一点么？谢谢

**Comment by zhangyuanwei** [comment]
访问 http://guzzoni.apple.com 这个能看到界面么 ？

**Comment by shenshen** [comment]
没起DNS 直接Host的，我看都没走onCommand方法，只能加些log自己调调了。
在做家电控制，用siri比较方便，唔。

**Comment by shenshen** [comment]
device.ask 等等接口都是不起作用的~ 已经走这个接口了

**Comment by zhangyuanwei** [comment]
“接口都是不起作用”什么表现？控制台输出什么？
 先试试 say 能用不。@shenshen

**Comment by shenshen** [comment]
所有的都不能用 iphone5 ,say  ask 等等能走完可是机器是没有反应的
也就是说目前device.writeClient 无效。
log了一下,device.serverResponse = [] 和null状态的切换貌似错的。
你那边是可以用的吗？

**Comment by shenshen** [comment]
024是默认的返回，被输出了 没有被截获，我改了些东西让他不发送到device也是不行，说明这个程序没有阻止任何默认行为。好难懂啊~
02:SetRestrictions
    003:AssistantLoaded
    004:SetConnectionHeader
005:SetRestrictions
006:ClearContext
007:SetBackgroundContext
008:StartSpeechRequest
009:SetRequestOrigin
010:SpeechPacket
011:SpeechPacket
012:SpeechPacket
013:SpeechPacket
014:SpeechPacket
015:SpeechPacket
016:SpeechPacket
017:SpeechPacket
018:SpeechPacket
019:SpeechPacket
020:SpeechPacket
021:SpeechPacket
022:FinishSpeech
    023:SpeechRecognized
    024:AddViews
    025:RequestCompleted
Client connect.
Client connect.
Server connect.
Server connect.
Server close.
Server close.
Client close.
Recycling resources.
Client close.
Recycling resources.
Server close.
Client close.
Recycling resources.
Client connect.
Client connect.
Server connect.
Server connect.
Server close.
Client close.
Recycling resources.
Server close.
Client close.
Recycling resources.

**Comment by zhangyuanwei** [comment]
我这是可以用的啊。iphone4S和new ipad都试过。

**Comment by shenshen** [comment]
我找台4S试一下吧

**Comment by shenshen** [comment]
4S也不行 
061:RollbackRequest
还没细看

**Comment by jnovack** [comment]
Is this solved?  Can we close?

**Comment by zhangyuanwei** [comment]
新的README应该已经解决了这个问题了。如果还不行的话，就用自带的证书吧。
