### ISSUE TITLE
错误错误：DEPTH_ZERO_SELF_SIGNED_CERT : nodejs 0.10.12

### ISSUE THREAD

**Issue by chesnel** [zhangyuanwei/node-siri#4]
你好，
我设法成功安装节点siri的，但现在我得到一个错误：

``` javascript
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: DEPTH_ZERO_SELF_SIGNED_CERT
```

我有nodejs版本10.12，我认为它来自TLS连接。
我试图安装的是旧版本0.8.15测试。

遗憾的文本，我使用谷歌翻译，希望能对你有所帮助:)

---

Hello,
I managed to successfully install node-siri, but now I get an error:

``` javascript
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: DEPTH_ZERO_SELF_SIGNED_CERT
```

I have nodejs version 10.12 and I think it comes from the tls connection.
I am trying to install an older version 0.8.15 test.

sorry for the text I use google translate, hoping for your help :)

**Comment by chesnel** [comment]
对不起，其他门柱。
我只是想与nodejs0.8.15，我没有的的错误DEPTH_ZERO_SELF_SIGNED_CERT，但这个职位：

``` javascript
events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: accept EMFILE
    at errnoException (net.js:769:11)
    at TCP.onconnection (net.js:1017:24)

```

我改变的ulimit9000的错误信息需要更长的时间才能到达。

任何想法？

---

Sorry for the other post.
I just tried with with nodejs 0.8.15, I do not have the error DEPTH_ZERO_SELF_SIGNED_CERT but this one post:

``` javascript
events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: accept EMFILE
    at errnoException (net.js:769:11)
    at TCP.onconnection (net.js:1017:24)

```

I changed the ulimit to 9000 but it does appear that the latest error message.

Any idea?

**Comment by chesnel** [comment]
Ok I found the solution for fix the bug with certificate with the version 0.10.12 of nodejs. In file siri.js line 93 I have change this : 

``` javascript
    //serverStream = tls.connect(SIRI_PORT, SIRI_SERVER, onServerConnect);
    serverStream = tls.connect({ host : SIRI_SERVER, port : SIRI_PORT, rejectUnauthorized: false },onServerConnect);
```

But I have  always an error with EMFILE : 

``` javascript
Error: connect EMFILE
```

it still takes a little time.

**Comment by chesnel** [comment]
I raise the question because I have followed the procedures @ jnovack and I always come across the error Error: DEPTH_ZERO_SELF_SIGNED_CERT

any idea?

**Comment by JBX028** [comment]
Hi,

I was face to a lot of issues the last days but not this one. At which moment this error is triggered ?

**Comment by chesnel** [comment]
when I try to apply to siri. I set up the dnsmasq. I took the certificate that is supplied directly with node-siri because if I generate with genca.sh I have a certificate error when testing with install.js. and I use the 0.10.7 version of nodejs

**Comment by JBX028** [comment]
Works fine for me but with node version 0.10.17
I don't know if there is a link but perhaps you can try to upgrade node ? Also, could you confirm that everything is green when you visit guzzoni.apple.com from your iDevice ? 
When you created the new certificate, did you put `guzzoni.apple.com` as a `common name` ?
Once the certificat generated, did you installad it by visiting `guzzoni.apple.com/ca` ?

**Comment by jnovack** [comment]
@chesnel Your iDevice should resolve `guzzoni.apple.com` as your `node-siri` server.  HOWEVER, your `node-siri` server should resolve `guzzoni.apple.com` to the internet.

You are receiving the `DEPTH_ZERO_SELF_SIGNED_CERT` error message because your `node-siri` server is resolving `guzzoni.apple.com` as your `node-siri` server. (It is trying to send packets to itself.)

Can you **Comment and Close** this ticket? I believe this is solved.

**Comment by chesnel** [comment]
> Your iDevice should resolve guzzoni.apple.com as your node-siri

yes... I'have add to my dnsmasq.conf the redirection address=/guzzoni.apple.com/(ipAdress of my computer)
and I define the dns in my iDevice pointing to the address ip of my computer..
But I always have the message error DEPTH_ZERO_SELF_SIGNED_CERT

I  don't know if I missed something...

**Comment by jnovack** [comment]
>  I don't know if I missed something...

Yes, you have:

> You are receiving the DEPTH_ZERO_SELF_SIGNED_CERT error message because your node-siri server is resolving guzzoni.apple.com as your node-siri server. (It is trying to send packets to itself.)

This is not an issue with `node-siri`, this is user error, we can further discuss this issue when you close the issue.

**Comment by chesnel** [comment]
Ok I understand is not something about node-siri but if I understand my server node-siri need to send the result not  to himself but to my iDevice ?

**Comment by jnovack** [comment]
If you are on your node-siri server, and you type `nslookup guzzoni.apple.com` and you get back the IP address of your node-siri server, **THIS IS WRONG**.

Your node-siri server needs to resolve `guzzoni.apple.com` out to the internet.  Change your DNS settings on your node-siri server to point to an external DNS server.

**Comment by chesnel** [comment]
This is true ... I forgot that... he had to point the address in /etc/resolv.conf to the external server (especially as it was the same for siriproxy). I put the google DNS 8.8.8.8.

Everything works perfectly now! Thank you very much. Hours of fun await me now
