### ISSUE TITLE
Text returned is concatenated without any space between the words

### ISSUE THREAD

**Issue by JBX028** [zhangyuanwei/node-siri#9]
Hi,

Strange behavior. The text returned by `cmd`, is concatenated and of course the regexp is not well evaluated.

`console.log("Speech Processed: " + cmd);`

When i say "Hello Siri", "HelloSiri" is displayed and in consequence not evaluated. I am a bit surprise because I didn't touched the source code. Is there something I do not well understand ?

To make it works, I have adjusted what `getRecognizedText` returns row 311 into `siri.js`. Instead of `return arr.join("");`, now `return arr.join(" ");` is returned in order to add a space between each word.

Thanks,

**Comment by zhangyuanwei** [comment]
Because in Chinese, there are no spaces between the words.... : (

**Comment by JBX028** [comment]
ah ah...so issue can be closed and I have even learned something today !!
